---
git:
  name: John Doe
  email: johndoe@example.com


kubernetes:
  # Releases: https://github.com/kubernetes/kubectl/tags
  # Last Updated: YYYY-MM-DD
  kubectl:
    version: "0.00"

  # Releases: https://github.com/kubernetes/minikube/releases
  # Last Updated: YYYY-MM-DD
  minikube:
    version: "0.0.0"
    checksum: "sha256:..."

  # Releases: https://github.com/tilt-dev/ctlptl/releases
  # Last Updated: YYYY-MM-DD
  ctlptl:
    version: "0.0.0"
    checksum: "sha256:..."

  # Releases: https://github.com/tilt-dev/tilt/releases
  # Last Updated: YYYY-MM-DD
  tilt:
    version: "0.0.0"
    checksum: "sha256:..."

