---
- name: Add flathub flatpak remote repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become_user: "{{ user.name }}"
