---
- name: Add Windsurf package signing key
  rpm_key:
    key: https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/RPM-GPG-KEY-windsurf


- name: Add Windsurf yum repository
  yum_repository:
    name: windsurf
    description: Windsurf Yum Repository
    baseurl: https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/repo/
    gpgcheck: True
    gpgkey: https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/RPM-GPG-KEY-windsurf


- name: Install windsurf
  package:
    name: windsurf
    state: latest
